### DISCUSSION TITLE
Trouble with Initial Setup

### DISCUSSION THREAD

**Discussion by zmweske** [seanmorley15/AdventureLog#526] [General]
I was getting a lot of errors setting up the stack when using a reverse proxy. Maybe the reverse proxy documentation could be cleared up, but what I found is that the backend needs the following: 
```yaml
      PUBLIC_URL: https://trips.${ROOT_DOMAIN}
      CSRF_TRUSTED_ORIGINS: https://trips.${ROOT_DOMAIN},http://192.168.1.101:8016  # ,http://adventurelog_backend:8000
      FRONTEND_URL: https://trips.${ROOT_DOMAIN}
```
and the following for the frontend:
```yaml
      PUBLIC_SERVER_URL: http://192.168.1.101:8016  # the bound port of the backend container, using the host's IP. using the commented part of the CSRF above did not work (PUBLIC_SERVER_URL: http://adventurelog_backend:8000 did not work under any circumstances)
      ORIGIN: https://trips.${ROOT_DOMAIN}
```

My overall docker-compose file is as follows: 
```yaml
  adventurelog_db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog_db
    << : *default-opts
    networks:
      - adventurelog
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: ${ADVENTURELOG__PGPASSWORD}
    volumes:
      - ${DIR_ROOT}/data/adventurelog/db:/var/lib/postgresql/data/
  adventurelog_backend:
    container_name: adventurelog_backend
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    << : *default-opts
    ports:
      - 8016:80
      # - 8017:8000
    networks:
      - adventurelog
      - traefik
    depends_on:
      - adventurelog_db
    links:
      - adventurelog_db:db
    environment:
      << : *common-vars
      DEBUG: True
      PGHOST: adventurelog_db
      PGDATABASE: database
      PGUSER: adventure
      PGPASSWORD: ${ADVENTURELOG__PGPASSWORD}
      SECRET_KEY: ${ADVENTURELOG__SECRET_KEY}
      DJANGO_ADMIN_USERNAME: admin
      DJANGO_ADMIN_PASSWORD: ${ADVENTURELOG__DJANGO_ADMIN_PASSWORD}
      DJANGO_ADMIN_EMAIL: admin@email.com
      PUBLIC_URL: https://trips.${ROOT_DOMAIN}
      CSRF_TRUSTED_ORIGINS: https://trips.${ROOT_DOMAIN},http://192.168.1.101:8016  # did NOT work: ,http://adventurelog_backend:80
      FRONTEND_URL: https://trips.${ROOT_DOMAIN}
    volumes:
      - ${DIR_ROOT}/data/adventurelog/media:/code/media/
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventurelog-api.tls=true
      - traefik.http.routers.adventurelog-api.entrypoints=websecure
      - traefik.http.routers.adventurelog-api.rule=Host(`trips.${ROOT_DOMAIN}`) && (PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))
      - traefik.http.services.adventurelog-api.loadbalancer.server.port=80
  adventurelog:
    container_name: adventurelog
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    << : *default-opts
    environment:
      << : *common-vars
      # PUBLIC_SERVER_URL: https://trips.${ROOT_DOMAIN}  # did NOT work
      # PUBLIC_SERVER_URL: http://adventurelog_backend:8000  # did NOT work
      PUBLIC_SERVER_URL: http://192.168.1.101:8016
      ORIGIN: https://trips.${ROOT_DOMAIN}
      # ORIGIN: http://192.168.1.101:8016  # did NOT work
      BODY_SIZE_LIMIT: 100000  # Infinity
    networks:  # - 8015:3000
      - adventurelog
      - traefik
    depends_on:
      - adventurelog_backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventurelog-web.tls=true
      - traefik.http.routers.adventurelog-web.entrypoints=websecure
      - traefik.http.routers.adventurelog-web.rule=Host(`trips.${ROOT_DOMAIN}`)  # && !(PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))
```

**Comment by filcuk** [comment]
Thanks for this, I've replicated your changes to the documented setup, and it finally works for me too.

```yaml
  adventurelog:
    container_name: adventurelog
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    restart: unless-stopped
    depends_on:
      - adventurelog-server
    networks:
      - internal
      - reverse_proxy
    environment:
      PUBLIC_SERVER_URL: "http://${ADVENTURELOG_SERVER_IP}:8000"
      ORIGIN: "https://adventurelog.${DOMAINNAME2}"
      BODY_SIZE_LIMIT: "100000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventurelog-rtr.entrypoints=https"
      - "traefik.http.routers.adventurelog-rtr.rule=Host(`adventurelog.${DOMAINNAME2}`) && !(PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))"
      - "traefik.http.routers.adventurelog-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.adventurelog-rtr.service=adventurelog-svc"
      - "traefik.http.services.adventurelog-svc.loadbalancer.server.port=3000"

  adventurelog-server:
    container_name: adventurelog-server
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    restart: unless-stopped
    depends_on:
      - adventurelog-db
    networks:
      internal:
        ipv4_address: ${ADVENTURELOG_SERVER_IP}
      reverse_proxy:
    expose:
      - 8000
    volumes:
      - ${DOCKERDIR}/appdata/adventurelog/media:/code/media
    environment:
      SECRET_KEY: ${ADVENTURELOG_SECRET_KEY}
      PUBLIC_URL: "https://adventurelog.${DOMAINNAME2}"
      FRONTEND_URL: "https://adventurelog.${DOMAINNAME2}"
      CSRF_TRUSTED_ORIGINS: "https://adventurelog.${DOMAINNAME2},http://adventurelog:8000"
      DJANGO_ADMIN_EMAIL: ${ADVENTURELOG_ADMIN_MAIL}
      DJANGO_ADMIN_USERNAME: ${ADVENTURELOG_ADMIN_USER}
      DJANGO_ADMIN_PASSWORD: ${ADVENTURELOG_ADMIN_PASS}
      PGHOST: "adventurelog-db"
      PGDATABASE: ${ADVENTURELOG_DB_NAME}
      PGUSER: ${ADVENTURELOG_DB_USER}
      PGPASSWORD: ${ADVENTURELOG_DB_PASS}
      DEBUG: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventurelogserver-rtr.entrypoints=https"
      - "traefik.http.routers.adventurelogserver-rtr.rule=Host(`adventurelog.${DOMAINNAME2}`) && (PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))"
      - "traefik.http.routers.adventurelogserver-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.adventurelogserver-rtr.service=adventurelogserver-svc"
      - "traefik.http.services.adventurelogserver-svc.loadbalancer.server.port=8000"
```
