### ISSUE TITLE
Images not compatible with Raspberry Pi (ARM Image)

### ISSUE THREAD

**Issue by wwwescape** [seanmorley15/AdventureLog#205]
I tried spinning up the containers via Docker Compose but got the following errors:

```
! web The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
! server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by seanmorley15** [comment]
Sorry about this! There is not currently an ARM image. I have added this to my issue tracker so I can work on getting one released. I will update this issues with progress!

**Comment by seanmorley15** [comment]
The latest image should now be ARM compatible. Can you try this out because I don't have an ARM machine! Thanks

**Comment by wwwescape** [comment]
Thanks! I got all the containers up and running and could access the homepage.

However, when I try to signup, I see this error on the UI:
![image](https://github.com/user-attachments/assets/366df262-469a-40ef-ae0f-fdd1802ad432)

And I see this in the Docker logs for the `web` container:
```
The origin to be set is: http://localhost:5251
Listening on 0.0.0.0:3000
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 172.75.0.3:5252
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.75.0.3',
    port: 5252
  }
}
[]
```

Here's my customized `docker-compose.yml`:
```yaml
version: "3.9"
services:
  web:
    container_name: adventurelog_web
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    environment:
      - PUBLIC_SERVER_URL=http://server:5252
      - ORIGIN=http://localhost:5251
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "5251:3000"
    depends_on:
      - server
  db:
    container_name: adventurelog_db
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    volumes:
      # - /home/pi/Docker/AdventureLog/postgres/data:/var/lib/postgresql/data/
      - postgres_data:/var/lib/postgresql/data/
  server:
    container_name: adventurelog_server
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=changeme123
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://localhost:5253'
      - CSRF_TRUSTED_ORIGINS=https://api.adventurelog.app,https://adventurelog.app
      - DEBUG=False
      - FRONTEND_URL='http://localhost:5251'
    ports:
      - "5252:8000"
    depends_on:
      - db
    volumes:
      - /home/pi/Docker/AdventureLog/media:/code/media/
  nginx:
    container_name: adventurelog_nginx
    image: nginx:latest
    ports:
      - "5253:80" # Using port 81 to avoid conflict with your existing setup
    volumes:
      - /home/pi/Docker/AdventureLog/media:/app/media
      - /home/pi/Docker/AdventureLog/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
volumes:
  postgres_data:
networks:
  default:
    name: adventurelog_default
    external: true
```

Any thoughts on how to solve this?
