### ISSUE TITLE
Registration is disabled

### ISSUE THREAD

**Issue by wardwygaerts** [seanmorley15/AdventureLog#294]
Although I didn't set the variable to disable registration, I get the following message in the logs and I'm not able to signup:

```
05-09-2024 22:29:40 The origin to be set is: http://localhost:9866
05-09-2024 22:29:40 Listening on 0.0.0.0:3000
05-09-2024 22:30:18 {
05-09-2024 22:30:18   is_disabled: false,
05-09-2024 22:30:18   message: 'Registration is disabled. Please contact the administrator if you need an account.'
05-09-2024 22:30:18 }
05-09-2024 22:30:18 []
05-09-2024 22:30:18 { user: null, is_disabled: false }
```

**Comment by seanmorley15** [comment]
Hmmm... This is strange, can you send your docker compose file so I can try and debug on my PC?
Thanks!

**Comment by wardwygaerts** [comment]
All settings are the defaults one I think, I first wanted to get it running before I integrate it in my Traefik setup.

```
services:
  web:
    container_name: adventurelog-frontend
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    hostname: adventurelog-frontend
    environment:
      - PUBLIC_SERVER_URL=http://server:8000 # MOST DOCKER USERS WILL NEVER NEED TO CHANGE THIS, EVEN IF YOU CHANGE THE PORTS
      - ORIGIN=http://localhost:9866
      - BODY_SIZE_LIMIT=Infinity # This is measured in bytes
    ports:
      - 9866:3000
    depends_on:
      - server
  db:
    container_name: adventurelog-db
    image: postgis/postgis:15-3.3
    hostname: adventurelog-db
    mem_limit: 1g
    cpu_shares: 1024
    environment:
      POSTGRES_DB: adventurelog
      POSTGRES_USER: adventureloguser
      POSTGRES_PASSWORD: adventurelogpass
    volumes:
      - $CONFIGDIR/adventurelog/db:/var/lib/postgresql/data/
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -q
        - -d
        - adventurelog
        - -U
        - adventureloguser
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped
  server:
    container_name: adventurelog-backend
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    hostname: adventurelog-backend
    environment:
      - PGHOST=db
      - PGDATABASE=adventurelog
      - PGUSER=adventureloguser
      - PGPASSWORD=adventurelogpass
      - SECRET_KEY=GesRc2FG3Hnzujz5WAAjGHBc3pm7
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=email@email.com
      - PUBLIC_URL='http://server:81'
      - CSRF_TRUSTED_ORIGINS=https://api.adventurelog.app,https://adventurelog.app
      - DEBUG=False
      - FRONTEND_URL='http://localhost:9866'
    ports:
      - 8669:8000
    depends_on:
      - db
    volumes:
      - $CONFIGDIR/adventurelog/server:/code/media/
  nginx:
    container_name: adventurelog-web
    image: nginx:latest
    ports:
      - 81:80
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - $CONFIGDIR/adventurelog/server:/app/media
      - $CONFIGDIR/adventurelog/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
networks: {}
```

**Comment by n00b12345** [comment]
Hi @wardwygaerts 

I was facing the same issue. Please change the URL address where you have included "localhost" to your server name (say "ubuntu-pc"). This will solve the issue.

**Comment by seanmorley15** [comment]
Yes, that is true. There are some ways to test it.
1. If you go to `https://api.adventurelog.app/auth/is-registration-disabled/` replacing with you backend domain, it should tell you if registration is disabled. Although this is likely a server connection issue because it queries this when the registration page is opened.
2. `ORIGIN=http://localhost:9866` - if this is not the address you are accessing from, it will bring up a cross site post error. Ensure you only access this app from this address
3. `PUBLIC_URL='http://server:81' this should be the public address to the nginx container, it should be accessible where you access your app. This is used for images.

I hope this helps!

**Comment by n00b12345** [comment]
Hello @seanmorley15

Is it possible to self host adventure log without a fully qualified domain name? I am only going to use this for personal use and will be using Tailscale to connect to it remotely.

**Comment by wardwygaerts** [comment]
I have it working with my Traefik setup (was not able to get it work locally).
Everything seems to be working, except the flags:
![image](https://github.com/user-attachments/assets/051619ad-fcef-4395-b4f1-54749572523d)

url of the images: https://adventurelog.domain.com/media/flags/**.png
I added the `nginx.conf` file.

nginx compose:
```
nginx:
    container_name: adventurelog-web
    image: nginx:latest
    networks:
      - proxy
    ports:
      - 81:80
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - $CONFIGDIR/adventurelog/web:/usr/share/nginx/html
      - $CONFIGDIR/adventurelog/media:/app/media/
      - $CONFIGDIR/adventurelog/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventurelog-nginx-rtr.entrypoints=https
      - traefik.http.routers.adventurelog-nginx-rtr.rule=Host(`adventurelog.$DOMAINNAME`)
        && PathPrefix(`/media`)
      - traefik.http.routers.adventurelog-nginx-rtr.tls=true
      - traefik.http.routers.adventurelog-nginx-rtr.middlewares=chain-oauth@file
      - traefik.http.routers.adventurelog-nginx-rtr.service=adventurelog-nginx-svc
      - traefik.http.services.adventurelog-nginx-svc.loadbalancer.server.port=3000
      - traefik.http.middlewares.adventurelog-nginx-strip.stripprefix.prefixes=/media
    depends_on:
      - server
```
