### ISSUE TITLE
[BUG] adventurelog-backend Error starting nginx

### ISSUE THREAD

**Issue by kceleslie** [seanmorley15/AdventureLog#366]
**Describe the bug**
Just upgraded to 0.7.1 and the adventurelog-backend wont start. I'm getting an error "Starting nginx: nginx failed"

**To Reproduce**
1.  Run the server

**Expected behavior**
Server starts

**Screenshots**

**Docker Compose**
I'm running mine within k3s, which i understand is probably not a supported. I'll paste my config and it's probably something i've got wrong. But it did work on previous versions. It would be helpful if i could get more logs to help pinpoint the problem. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adventurelogserver
  name: adventurelogserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventurelogserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adventurelogserver
    spec:
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      containers:
        - env:
          - name: TZ
            value: "America/Chicago"
          - name: PGHOST
            value: "adventurelogdb"
          - name: PGDATABASE
            value: database
          - name: PGUSER
            value: "adventurelog"
          - name: PGPASSWORD
            value: "xxxxxxxxxx"
          - name: SECRET_KEY
            value: xxxxxxx
          - name: DJANGO_ADMIN_USERNAME
            value: xxxxxxxxxx                                                                                                                        
          - name: DJANGO_ADMIN_PASSWORD
            value: xxxxxxxxxxxxxxxxxx                                                                                                                        
          - name: DJANGO_ADMIN_EMAIL
            value: xxxxxxxxxx@gmail.com
          - name: PUBLIC_URL
            value: 'http://trips.xxxxxxxxxxxxx.xyz'                            
          - name: CSRF_TRUSTED_ORIGINS
            value: "http://trips.xxxxxxxxxxx.xyz,http://0.0.0.0:8080"
          - name: DEBUG
            value: "True"
          - name: FRONTEND_URL
            value: 'http://trips.xxxxxxxxxxxxxxxx.xyz'
          image: ghcr.io/seanmorley15/adventurelog-backend:latest
          name: adventurelog
          ports:
            - containerPort: 80
          #  - containerPort: 22
          volumeMounts:
            - mountPath: /code/media
              name: adventurelog-nfs
            #- mountPath: /old
            #  name: adventurelog-nfs
          #securityContext:
          #  allowPrivilegeEscalation: false
      restartPolicy: Always
      volumes:
        - name: adventurelog-nfs
          nfs:
            server: 192.168.1.120
            path: /volume1/kubernetes/adventurelog/server
```

**Additional context**
