### ISSUE TITLE
[BUG] Add social application form has empty Provider list

### ISSUE THREAD

**Issue by mpfl** [seanmorley15/AdventureLog#474]
**Describe the bug**
When trying to add a new OIDC provider on a fresh installation of AdventureLog 0.8.0, the Provider list is empty.

**To Reproduce**
1. Get [docker-compose-traefik.yaml](https://github.com/seanmorley15/AdventureLog/blob/main/docker-compose-traefik.yaml)
2. Customise for local network conditions
3. `docker compose up -d`
4. Navigate to https://adventurelog.redacted
5. Log in as new admin user
6. Navigate to https://adventurelog.redacted/admin
7. Under Social Accounts, click Add next to Social applications

**Expected behavior**
The Provider list should have at least `GitHub `and `OpenID Connect` as shown in the documentation.

**Screenshots**

![Image](https://github.com/user-attachments/assets/18823722-93aa-483f-8fb0-e193f77cffc1)

**Docker Compose**

```yaml
services:
  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: redacted # Replace with the actual password
    volumes:
      - /home/adventurelog/data:/var/lib/postgresql/data/

  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:v0.8.0
    restart: unless-stopped
    networks:
      - default
      - web
    environment:
      PUBLIC_SERVER_URL: "http://server:8000"
      BODY_SIZE_LIMIT: Infinity
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventurelogweb.entrypoints=websecure"
      - "traefik.http.routers.adventurelogweb.rule=Host(`adventurelog.redacted `) && !(PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))" # Replace with your domain
      - "traefik.http.routers.adventurelogweb.middlewares=security@docker"
    depends_on:
      - server

  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:v0.8.0
    restart: unless-stopped
    networks:
      - default
      - web
    environment:
      PGHOST: "db"
      PGDATABASE: "database"
      PGUSER: "adventure"
      PGPASSWORD: redacted  # Replace with the actual password
      SECRET_KEY: redacted  # Replace with the actual secret key
      DJANGO_ADMIN_USERNAME: "redacted"
      DJANGO_ADMIN_PASSWORD: redacted  # Replace with the actual admin password
      DJANGO_ADMIN_EMAIL: "redacted" # Replace with your email
      PUBLIC_URL: "https://adventurelog.redacted " # Replace with your domain
      CSRF_TRUSTED_ORIGINS: "https://adventurelog.redacted " # Replace with your domain
      DEBUG: "true"
      FRONTEND_URL: "https://adventurelog.redacted " # Replace with your domain
      DISABLE_REGISTRATION: True
    # OPTIONAL: Set the message to display when registration is disabled
      DISABLE_REGISTRATION_MESSAGE: 'Registration is disabled for this instance of AdventureLog.'
      EMAIL_BACKEND: 'email'
      EMAIL_HOST: redacted 
      EMAIL_USE_TLS: False
      EMAIL_PORT: 587
      EMAIL_USE_SSL: True
      EMAIL_HOST_USER: server@redacted 
      EMAIL_HOST_PASSWORD: redacted 
      DEFAULT_FROM_EMAIL: adventurelog@redacted 
    volumes:
      - /home/adventurelog/media:/code/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventurelogserver.entrypoints=websecure"
      - "traefik.http.routers.adventurelogserver.rule=Host(`adventurelog.redacted`) && (PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))" # Replace with your domain
      - "traefik.http.routers.adventurelogserver.middlewares=security@docker"
    depends_on:
      - db

networks:
  web:
    external: true
```

**Additional context**
Removing the security@docker middleware has no effect.
