### ISSUE TITLE
[DEPLOYMENT]Unable to connect to external Postgres DB

### ISSUE THREAD

**Issue by ruehcep** [seanmorley15/AdventureLog#494]
## Unable to connect to external Postgres DB
I have a Postgres database outside the docker compose I would like to use. I am using it successfully for other docker but adventure log is giving the error, that it can connect.

## Database configuration
```
  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    environment:
      - PGHOST=postgres://192.168.4.81:8500
      - PGDATABASE=adventurelog_db
      - PGUSER=***
      - PGPASSWORD=***
      - ...
```

## AdventureLog Backend logs

```
Starting nginx: nginx.

PostgreSQL is unavailable - sleeping

PostgreSQL is unavailable - sleeping
...
```

Anyone else using an external database with adventurelog?
