### ISSUE TITLE
[DEPLOYMENT] Images not loading unless Debug=True

### ISSUE THREAD

**Issue by Ryan24b** [seanmorley15/AdventureLog#542]
## Explain your issue
I've been troubleshooting why the Flags on the World Travel page would not load and show as "No image available"
During this, I found that changing Debug=True allows the Images to load, but as soon as it's back to False, they don't work. 

This is the same for any images I upload. They will upload without a problem but only display when the server is Debug=True.

Visiting https://adventurelogapi.mydomain.com/media/flags/af.png results in a 404 Not found from nginx

I have Aventurelog exposed through a Cloudflare Tunnel
Front: adventurelog.mydomain.com
Back: adventurelogapi.mydomain.com

## Provide an **obfuscated** `docker-compose.yml`

services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    environment:
      - PUBLIC_SERVER_URL=http://server:8000 # Should be the service name of the backend with port 8000, even if you change the port in the backend service
      - ORIGIN=https://adventurelog.mydomain.com
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - 8015:3000
    depends_on:
      - server

  db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: adventurelog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - /mnt/nvme/apps/docker/adventurelog/db:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    environment:
      - DISABLE_REGISTRATION=true
      - PGHOST=db
      - PGDATABASE=adventurelog
      - PGUSER=user
      - PGPASSWORD=pass
      - SECRET_KEY=secret
      - DJANGO_ADMIN_USERNAME=user
      - DJANGO_ADMIN_PASSWORD=pass
      - DJANGO_ADMIN_EMAIL=email@gmail.com
      - PUBLIC_URL= https://adventurelogapi.mydomain.com # Match the outward port, used for the creation of image urls
      - CSRF_TRUSTED_ORIGINS=http://localhost:8015,http://localhost:8016,https://adventurelog.mydomain.com,https://adventurelogapi.mydomain.com # Comma separated list of trusted origins for CSRF
      - DEBUG=False
      - FRONTEND_URL=https://adventurelog.mydomain.com # Used for email generation. This should be the url of the frontend
    ports:
      - 8016:80
    depends_on:
      - db
    volumes:
      - /mnt/nvme/apps/docker/adventurelog/media:/code/media/

## Provide any necessary logs from the containers and browser

The logs don't show any issues but will paste them anyway. 

**Backend:**

Starting nginx: nginx.
PostgreSQL is up - continuing...
Operations to perform:
  Apply all migrations: account, admin, adventures, auth, authtoken, contenttypes, integrations, mfa, sessions, sites, socialaccount, users, worldtravel
Running migrations:
  No migrations to apply.
Creating superuser...
Superuser already exists.
Latest country, region, and state data already downloaded.

**DB:**

PostgreSQL Database directory appears to contain a database; Skipping initialization
2025-03-23 06:22:37.115 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2025-03-23 06:22:37.115 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-03-23 06:22:37.115 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-03-23 06:22:37.123 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-03-23 06:22:37.130 UTC [29] LOG:  database system was shut down at 2025-03-23 06:22:06 UTC
2025-03-23 06:22:37.136 UTC [1] LOG:  database system is ready to accept connections

**Frontend:**

The origin to be set is: https://adventurelog.mydomain.com

Listening on 0.0.0.0:3000

**Comment by Ryan24b** [comment]
I appear to have solved it by removing /code/ from the server volume

- /mnt/nvme/apps/docker/adventurelog/media:/code/media/ -> - /mnt/nvme/apps/docker/adventurelog/media:/media/

**Comment by filcuk** [comment]
I believe this is still true in the latest release. I receive 500 on images otherwise whilst everything else works.

**Comment by ivanvmoreno** [comment]
I can replicate this. Version `v0.9.0`, no images load on the browser unless running the backend container with the environment variable `DEBUG=True`.

**Comment by Ryan24b** [comment]
I didn't realise I had closed this. I've opened it again after confirming that the problem still exists. 

I tried `v0.8.0`, and the problem existed there, too.

**Comment by Jacob-Lasky** [comment]
I had the same problem. I think the issue was that my reverse proxy wasn't able to see the images in /media.

I was able to get this to work _without_ setting DEBUG=True by making sure that my NginxProxyManager was on the same network as the adventurelog stack:
`docker network connect adventurelog_default NginxProxyManager`

And then adding this as a Custom Nginx Configuration
```
location /media/ {
    proxy_pass http://adventurelog-backend:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

Note that the `http://adventurelog-backend:80` may be slightly different for you. That's what my backend container is named and that's also the port that it's running on. I think by default it runs on 8000.

**Comment by Aesgarth** [comment]
I have a workaround for this issue that I'm using with Traefik.  that involves using a dedicated Nginx container to serve the media files.
When DEBUG=False, Django does not serve media files itself for production. While the AdventureLog Traefik example routes /media/ to the backend, the Django application (as is common) might not be configured to serve these files directly in production mode. This setup offloads media serving to a dedicated, lightweight Nginx container.

This solution assumes:
You are using Traefik as your main reverse proxy.
Your Django backend (server service in AdventureLog's case) and the new Nginx media-server share a common Docker volume for media files.
You will adjust your Traefik labels so that requests to /media/ go to this new Nginx media-server instead of the Django backend.
Here are the example configurations:

Add the following service definition to your docker-compose.yml. This media-server will be a new Nginx container specifically for serving your media files
```
# In your docker-compose.yml

services:
  # ... your existing db, backend (e.g., 'server'), and frontend (e.g., 'web') services ...

  media-server:
    image: nginx:alpine 
    container_name: adventurelog-media-server 
    restart: unless-stopped
    volumes:
      # Mount the shared media volume (read-only for Nginx)
      # 'adventurelog_media' should be the same named volume your Django backend saves uploads to.
      - adventurelog_media:/usr/share/nginx/html/media:ro
      # Mount your Nginx configuration file for this media server.
      # The file on the host should be created at the specified path.
      - /path/on/your/docker_host/to/nginx-media.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - your_traefik_network # e.g., 'proxy', 'web' - the network Traefik can see
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=your_traefik_network" # Must match the network name above

      # Traefik router for media requests
      - "traefik.http.routers.adventurelog-media.rule=Host(`your-domain.com`) && PathPrefix(`/media`)"
      - "traefik.http.routers.adventurelog-media.entrypoints=your_https_entrypoint_name" # e.g., 'websecure', 'https'
      - "traefik.http.routers.adventurelog-media.tls=true"
      - "traefik.http.routers.adventurelog-media.tls.certresolver=your_traefik_certresolver_name" # e.g., 'letsencrypt', 'myresolver'
      - "traefik.http.routers.adventurelog-media.priority=15" # Higher priority for this specific path

      # Traefik service definition for this media server
      - "traefik.http.services.adventurelog-media.loadbalancer.server.port=80" # Nginx listens on port 80 internally

```
Important notes for the docker-compose.yml section:

Replace your-domain.com, /path/on/your/docker_host/to/nginx-media.conf, your_traefik_network, your_https_entrypoint_name, and your_traefik_certresolver_name with your actual values.
The volume adventurelog_media must be the same named volume that your Django backend service uses for its MEDIA_ROOT.
Ensure this media-server and your Traefik container are on the same Docker network (your_traefik_network).


Create an Nginx configuration file on your Docker host (e.g., at /path/on/your/docker_host/to/nginx-media.conf). This file tells Nginx how to serve the media files.
File content for nginx-media.conf:
```
# nginx-media.conf
# This file is mounted into the media-server Nginx container.

server {
    listen 80 default_server; # Nginx listens on port 80 inside the container

    # Optional: Set a server_name, though for internal routing via Traefik it's less critical.
    # server_name your-domain.com;
    server_name _;

    # Optional: Define log paths (ensure Nginx process has permissions to write if not default paths)
    access_log /var/log/nginx/media.access.log;
    error_log /var/log/nginx/media.error.log;

    # This location block handles requests for /media/
    location /media/ {
        # 'alias' points to the directory *inside the Nginx container*
        # where the media files are mounted. This must match the volume mount.
        alias /usr/share/nginx/html/media/;

        # Optional: Disable directory listing for security
        autoindex off;

        # Optional: Add browser caching headers (e.g., cache for 7 days)
        expires 7d;
        add_header Cache-Control "public";

        # Optional: Improves how Nginx serves static files.
        # open_file_cache max=1000 inactive=20s;
        # open_file_cache_valid 30s;
        # open_file_cache_min_uses 2;
        # open_file_cache_errors on;

        # Optional: Try to serve the file, then directory, or return 404.
        # Useful if you have index files within media subdirectories.
        # try_files $uri $uri/ =404;
    }

    # Optional: A default handler for any other requests to this Nginx instance
    location / {
        return 404; # Or serve a specific "Not Found" page
    }
}
```
Important notes for the nginx-media.conf file:

The alias /usr/share/nginx/html/media/; path inside the location /media/ block must correspond to the target path of your adventurelog_media volume mount in the media-server service definition in your docker-compose.yml.
This configuration is minimal and focused on serving media. You can add more Nginx directives as needed (e.g., more advanced caching, security headers).


Finally, you need to modify the Traefik labels for your main Django backend service (usually named server or backend in AdventureLog setups) in your docker-compose.yml to remove the PathPrefix(\/media`)from its routing rule. This ensures Traefik doesn't send/media/` requests to Django anymore.

Example: Before (Backend handles /media/
```
labels:
  - "traefik.http.routers.your-backend-router.rule=Host(`your-domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/media`) || PathPrefix(`/static`))"
```
Example: After (Backend NO LONGER handles /media/)

```
labels:
  # ... other Traefik labels for your backend ...
  - "traefik.http.routers.your-backend-router.rule=Host(`your-domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`))" # Or whatever other paths it handles
  # ...
```
Also ensure your frontend Traefik rule excludes /media/ if it's a general catch-all rule for the domain."

After making these changes to your docker-compose.yml and creating the Nginx config file, redeploy your stack. Traefik should then route /media/ requests to the new Nginx media-server, which will serve the files directly from the shared volume, and this works correctly when Django's DEBUG mode is False.

**Comment by gabriel-stackhouse** [comment]
I was able to resolve the issue using a variation of @Aesgarth and @Jacob-Lasky's solutions, but using Caddy as the webserver:

```yaml
# docker-compose.yml
services:
 
  # existing services (server, db, web)

  caddy:
    image: docker.io/library/caddy:2
    container_name: adventurelog-caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "${CADDY_PORT:-8017}:80"
    volumes:
      - ${APPDATA_DIR}/caddy/caddy:/etc/caddy
      - ${APPDATA_DIR}/caddy/data:/data
      - ${APPDATA_DIR}/caddy/config:/config
      - ${APPDATA_DIR}/media:/srv/media:ro  # Host path must match the media directory in the server
    depends_on:
      - web
 ```

And then a simple Caddyfile in `${APPDATA_DIR}/caddy/caddy`:

```caddy
http://:80 {
        
        # Serve uploaded files & flag images
        handle_path /media/* {
                root * /srv/media
                file_server
        }

        # Frontend routing
        @frontend {
                not path /media* /admin* /static* /accounts*
        }
        reverse_proxy @frontend web:3000

        # Backend routing (API, admin, etc.)
        reverse_proxy server:8000
}
```

A bonus of this setup is that only one port (`8017`) needs to be exposed through my Cloudflare tunnel - the internal Caddy webserver handles all the routing after that. Slick!
