### ISSUE TITLE
[DEPLOYMENT] Issue with Images not showing up

### ISSUE THREAD

**Issue by Companion83** [seanmorley15/AdventureLog#582]
I successfully deployed AdventureLog on my server with public DNS. Everything works ok, except that images do not load. I use traefik v3 as a reverse proxy.

All uploaded images (webp) as well as the flags (png) on World Travel tab show a broken link icon with text 'No image available' 

My docker-compose file (part):

```yaml
adventurelog-db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: your_postgres_password # Replace with the actual password
    volumes:
      - adventurelog-data:/var/lib/postgresql/data/
    networks:
      - traefik

  adventurelog-web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:v0.9.0
    restart: unless-stopped
    environment:
      PUBLIC_SERVER_URL: "http://adventurelog-server:8000"
      ORIGIN: "https://MY-DOMAIN"
      BODY_SIZE_LIMIT: "12582912" # 12MByte
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adventurelogweb.loadbalancer.server.port=3000"
      - "traefik.http.routers.adventurelogweb.entrypoints=https"
      - "traefik.http.routers.adventurelogweb.rule=Host(`MY-DOMAIN`) && !(PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))" # Replace with your domain
      - "traefik.http.routers.adventurelogweb.tls=true"
      - "traefik.http.routers.adventurelogweb.tls.certresolver=http"
    depends_on:
      - adventurelog-server
    networks:
      - traefik

  adventurelog-server:
    image: ghcr.io/seanmorley15/adventurelog-backend:v0.9.0
    restart: unless-stopped
    environment:
      PGHOST: "adventurelog-db"
      PGDATABASE: "database"
      PGUSER: "adventure"
      PGPASSWORD: your_postgres_password # Replace with the actual password
      SECRET_KEY: your_secret_key # Replace with the actual secret key
      DJANGO_ADMIN_USERNAME: "admin"
      DJANGO_ADMIN_PASSWORD: admin # Replace with the actual admin password
      DJANGO_ADMIN_EMAIL: "adventurelog-admin@yourdomain.com" # Replace with your email
      PUBLIC_URL: "https://MY-DOMAIN" # Replace with your domain
      CSRF_TRUSTED_ORIGINS: "https://MY-DOMAIN" # Replace with your domain
      DEBUG: "true"
      FRONTEND_URL: "https://MY-DOMAIN" # Replace with your domain
      DISABLE_REGISTRATION: True
      # OPTIONAL: Set the message to display when registration is disabled
      # DISABLE_REGISTRATION_MESSAGE: 'Registration is disabled for this instance of AdventureLog.'
    volumes:
      - adventurelog-media:/code/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventurelogserver.entrypoints=https"
      - "traefik.http.services.adventurelogserver.loadbalancer.server.port=8000"
      - "traefik.http.routers.adventurelogserver.rule=Host(`MY-DOMAIN`) && ( PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))" # Replace with your domain
      - "traefik.http.routers.adventurelogserver.tls=true"
      - "traefik.http.routers.adventurelogserver.tls.certresolver=http"
    depends_on:
      - adventurelog-db
    networks:
      - traefik
``

Server and web container do not show any suspicious logs. 

Example resource shown in the network tab from developer tools have no content-lenght, e.g. https://MY-DOMAIN/media/flags/ye.png:

**response header:**
content-length:
0
content-type:
date:
Tue, 22 Apr 2025 16:50:48 GMT
server:
gunicorn
set-cookie:
sessionid=olr79hj01op697q3bp8x5i6h2jm0j1rm; Domain=.abenteuer-blog.spdns.eu; expires=Tue, 06 May 2025 16:50:48 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax; Secure
vary:
Cookie, origin
x-accel-redirect:
/protectedMedia/flags/ye.png

x-frame-options:
DENY

Any help on this issue would be great.

**Comment by seanmorley15** [comment]
Hi @Companion83, here are some debugging tips to help get images showing.

1. Go to `/api/countries` on the frontend and see what URLs the api is returning for the flag images. Visit that URL and see if the image is displayed. If it's displayed on that URL try again with a cache clear.
2. Check the `PUBLIC_URL` and make sure its the backend URL ex `https://adventure-api.mydomain.com`

Let me know if this helps!

**Comment by Companion83** [comment]
Hi @seanmorley15,
thank you for your quick response! I checked /api/countries and retrieved a list containing:

```json
[
  {
  "id": 1,
  "flag_url": "https://MY-DOMAIN/media/flags/af.png",
  "num_regions": 33,
  "num_visits": 0,
  "name": "Afghanistan",
  "country_code": "AF",
  "subregion": "Southern Asia",
  "capital": "Kabul",
  "longitude": "65.000000",
  "latitude": "33.000000",
  "insert_id": null
 },
...
]
```

I can verify that the links do have the correct domain. When I try a link I get a blank page. Inspecting the blank page with the browser developer tools shows different response and request headers than what I get from hosting and accessing AdventureLog locally only.

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/ac50d6b7-9797-4ee2-ad7a-e6bdd77040f6" />

Hosting locally:

<img width="810" alt="Image" src="https://github.com/user-attachments/assets/e757cdb1-640c-4a81-b88f-f20e9170b7c5" />

Could it be related to traefik?

I also found an unrelated-looking error in the frontend logs:

```
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5591:19)
    at successSteps (node:internal/deps/undici/undici:5562:27)
    at fullyReadBody (node:internal/deps/undici/undici:1665:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5571:7)
    at async load (file:///app/build/server/chunks/4-DD5Gozym.js:31:27)
    at async load_server_data (file:///app/build/server/index.js:1203:18)
    at async Promise.all (index 1)
    at async render_data (file:///app/build/server/index.js:2433:19)
```
I appreciate your help!

**Comment by seanmorley15** [comment]
Hi @sdeveer, are you able to check your `PUBLIC_URL` in the backend container and make sure its set to the public URL to the backend container? Ex `https://adventureapi.domain.com`. This is needed because it creates the URLs to the images. 
Check out the guide here for more debug steps: [https://adventurelog.app/docs/troubleshooting/no_images.html](https://adventurelog.app/docs/troubleshooting/no_images.html)\
Let me know how it goes!

**Comment by sdeveer** [comment]
You solved it. 

You triggered me with your remark thanks! The port wasn’t forwarded fro the backend so the firewall blocked the image… not the server!

Thanks!

 

Van: Sean Morley ***@***.***> 
Verzonden: zaterdag 31 mei 2025 21:45
Aan: seanmorley15/AdventureLog ***@***.***>
CC: sdeveer ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [seanmorley15/AdventureLog] [DEPLOYMENT] Issue with Images not showing up (Issue #582)

 

  <https://avatars.githubusercontent.com/u/98704938?s=20&v=4> seanmorley15 left a comment (seanmorley15/AdventureLog#582) <https://github.com/seanmorley15/AdventureLog/issues/582#issuecomment-2925660116> 

Hi @sdeveer <https://github.com/sdeveer> , are you able to check your PUBLIC_URL in the backend container and make sure its set to the public URL to the backend container? Ex https://adventureapi.domain.com. This is needed because it creates the URLs to the images.
Check out the guide here for more debug steps: https://adventurelog.app/docs/troubleshooting/no_images.html
Let me know how it goes!

**Comment by Jerome1998** [comment]
I have the exact same issue as @Companion83. I tried your debugging tips @seanmorley15 but I get the same results as @Companion83. The image url seems to be the correct one but it won't get loaded. 
Using Treafik in version 3.4 too, but I tried the version (`v2.11`) of the Treafik example compose file and that changed nothing.

This is my compose file, very similar to the one from @Companion83 
```yaml
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog-db
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: adventure
    volumes:
      - /volume1/docker/adventurelog/postgres:/var/lib/postgresql/data/
    networks:
      - adventurelog

  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - adventurelog
      - traefik
    volumes:
      - /volume1/docker/adventurelog/media:/code/media/
    environment:
      - TZ=Europe/Berlin
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=adventure
      - SECRET_KEY=Key
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=Password
      - DJANGO_ADMIN_EMAIL=admin@adventurelog.domain.com
      - PUBLIC_URL=https://adventurelog.domain.com
      - CSRF_TRUSTED_ORIGINS=https://adventurelog.domain.com
      - DEBUG=False
      - FRONTEND_URL=https://adventurelog.domain.com
      - DISABLE_REGISTRATION=True
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventurelog-server.rule=Host(`adventurelog.domain.com`) && (PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))
      - traefik.http.routers.adventurelog-server.entrypoints=websecure
      - traefik.http.routers.adventurelog-server.tls=true
      - traefik.http.routers.adventurelog-server.tls.certresolver=lets-encrypt
      - traefik.http.routers.adventurelog-server.service=adventurelog-server
      - traefik.http.services.adventurelog-server.loadbalancer.server.port=8000

  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - TZ=Europe/Berlin
      - PUBLIC_SERVER_URL=http://server:8000
      - ORIGIN=https://adventurelog.domain.com
      - BODY_SIZE_LIMIT=100000
    networks:
      - adventurelog
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventurelog-web.entrypoints=websecure
      - traefik.http.routers.adventurelog-web.rule=Host(`adventurelog.domain.com`) && !(PathPrefix(`/media`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))
      - traefik.http.routers.adventurelog-web.tls=true
      - traefik.http.routers.adventurelog-web.tls.certresolver=lets-encrypt
      - traefik.http.routers.adventurelog-web.service=adventurelog-web
      - traefik.http.services.adventurelog-web.loadbalancer.server.port=3000

networks:
  traefik:
    external: true
  adventurelog:
    name: adventurelog
```

Just removed all relevant passwords and secrets and replaced my actual domain with `domain.com`.

**Comment by Companion83** [comment]
Hi @Jerome1998,
I solved my problem. I made a mistake when renaming the containers and failed to accommodate for it in the environment variables. Looking at your compose file, I think you made a similar mistake. Your containers are called 'adventurelog-frontend' and 'adventurelog-backend', but in service.web you are referring to `PUBLIC_SERVER_URL=http://server:8000`. In your case, it should be `PUBLIC_SERVER_URL=adventurelog-backend:8000`.
I stumbled across this error when I opened a shell inside the containers and tested whether they could reach each other through their respective Docker network domain names. Just for future reference.

**Comment by Jerome1998** [comment]
Hey @Companion83, 
thanks for the suggestion but the result is exactly the same.
Could your share your updated and working compose file? Maybe that helps to figure out the problem 🤔

**Comment by oohhddaanngg** [comment]
> Hey [@Companion83](https://github.com/Companion83), thanks for the suggestion but the result is exactly the same. Could your share your updated and working compose file? Maybe that helps to figure out the problem 🤔

I am using Traefik 3.4 and was having a very hard time getting images to display.  The issue is that Adventure Log's nginx is using X-Accel-Redirect, but the internal redirect path /protectedMedia/ doesn't work through Traefik.

What worked for me is:

(edit to your own install directory if needed)

`nano /opt/adventurelog/nginx-media.yml`

(add this to the contents of your nginx-media.yml, replacing anything that says "xxxxx" with your own personal details)

```
services:
  nginx-media:
    image: nginx:alpine
    container_name: adventurelog-nginx-media
    restart: unless-stopped
    volumes:
      - /opt/adventurelog/media:/usr/share/nginx/html/media:ro
    networks:
      - xxxxx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adventurelog-media-direct.rule=Host(`xxxxx.xxxxx.xxxxx`) && PathPrefix(`/media`)"
      - "traefik.http.routers.adventurelog-media-direct.entrypoints=websecure"
      - "traefik.http.routers.adventurelog-media-direct.tls.certresolver=cfdns"
      - "traefik.http.services.adventurelog-media-direct.loadbalancer.server.port=80"

networks:
  xxxxx:
    external: true
```

Then start the container:

`cd /opt/adventurelog
docker compose -f nginx-media.yml up -d`

Then edit your Traefik rule:

(change to your traefik install directory if needed)

`nano /opt/traefik/rules/adventurelog.yml`

change your backend router rule to:

(replacing anything that says "xxxxx" with your own personal details)

`rule: "Host(`xxxxx.xxxxx.xxxxx`) && (PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/accounts`))"`

That's what worked for me, hopefully it helps someone.
