### ISSUE TITLE
[DEPLOYMENT] Can't get it to run on ZimaOS

### ISSUE THREAD

**Issue by CogZog** [seanmorley15/AdventureLog#671]
I have tried several different ways to install this on ZimaOS, a Debian based NAS OS. I used it's built in App installer and also tried using Portainer to install it too to no avail. I will attach my logs as below.

[adventurelog-db log.pdf](https://github.com/user-attachments/files/20741267/adventurelog-db.log.pdf)

[adventurelog-backend log.pdf](https://github.com/user-attachments/files/20741268/adventurelog-backend.log.pdf)

[adventurelog-frontend log.pdf](https://github.com/user-attachments/files/20741269/adventurelog-frontend.log.pdf)

Many thanks,
Colin.

**Comment by seanmorley15** [comment]
Hi @CogZog!

Are you able to check the `PUBLIC_SERVER_URL` in the frontend? Make sure this is `http://server:8000`

From the logs it seems like the frontend cannot connect to the backend. Although the backend logs do not seem to be a complete startup, either the container has not started up fully or they were captured before a complete startup. The backend container has started once a big ADVENUTRELOG has printed across the screen. Also, is the error right after clicking login/signup pages or after attempting to actually login? Are you able to double check these things for me and let me know what happens!

Thanks

**Comment by CogZog** [comment]
Hi, thanks for the reply. I have changed the PUBLIC_SERVER_URL back to
http://server:8000 as I did try various entries to try and get it working.
I've tried running the app again but still the same result unfortunately.

The 500: Internal Error appears as soon as I click on either of the Login
or Signup buttons so it's definitely a connection issue between the
frontend and the backend?

Many thanks.

**Comment by seanmorley15** [comment]
Sorry to hear that didn't work. Are you using a docker compose and enc file? If so can you provide a copy of them without credentials so I can help debug?
Thanks

**Comment by CogZog** [comment]
Hi, I'm using Portainer currently. Here is my .env entries;

PUBLIC_SERVER_URL=http://server:8000 # PLEASE DON'T CHANGE :) - Should be
the service name of the backend with port 8000, even if you change the port
in the backend service. Only change if you are using a custom more complex
setup.
ORIGIN=http://192.168.1.84:8015
BODY_SIZE_LIMIT=Infinity
FRONTEND_PORT=8015
PGHOST=db
POSTGRES_DB=database
POSTGRES_USER=cog
POSTGRES_PASSWORD=M0r9an11
SECRET_KEY=PyMAtB9aIBeBjXqaJKz1Y645EDpGJQaLRO1gljVx35bj9zX3VUb48tHQ4Kcux8aO
DJANGO_ADMIN_USERNAME=admin
DJANGO_ADMIN_PASSWORD=admin
***@***.***
PUBLIC_URL=http://192.168.1.84:8016 # Match the outward port, used for the
creation of image urls
CSRF_TRUSTED_ORIGINS=http://192.168.1.84:8016,http://192.168.1.84:8015
DEBUG=False
FRONTEND_URL=http://192.168.1.84:8015 # Used for email generation. This
should be the url of the frontend
BACKEND_PORT=8016
DISABLE_REGISTRATION=False

My docker-compose.yml entries;

services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${FRONTEND_PORT:-8015}:3000"
    depends_on:
      - server

  db:
    image: postgis/postgis:16-3.5
    container_name: adventurelog-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${BACKEND_PORT:-8016}:80"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/

volumes:
  postgres_data:
  adventurelog_media:

Many thanks.

**Comment by seanmorley15** [comment]
@CogZog, your compose seems to be correct for your setup. I wonder if the backend is not starting properly? Are you able to try restarting containers and wait and see if it starts up. You will know it started up if you can visit http://192.168.1.84:8016 - and then login to the admin panel. Let me know if you can do this. This will help determine the root cause :)

**Comment by ChristopheRoyer21** [comment]
I'm having the same issue, but on RaspberryPiOS
I feel like we take the compose.yml from the same place since it's mostly the same. Main difference is that I use localhost instead of the actual IP Adress. The application starts, but whenever I try to login or create an account, I have the following error

![Image](https://github.com/user-attachments/assets/e801f29f-010d-434f-9bdf-46142c675e10)

**Comment by seanmorley15** [comment]
Hi @ChristopheRoyer21, are you able to possibly share a redacted version of your compose and the logs from the backend container so I can help debug more, likely it just a small issue that can be fixed quicky :)

**Comment by ChristopheRoyer21** [comment]
> Hi [@ChristopheRoyer21](https://github.com/ChristopheRoyer21), are you able to possibly share a redacted version of your compose and the logs from the backend container so I can help debug more, likely it just a small issue that can be fixed quicky :)

Indeed, this is prbably a simple issue. At some point, I managed to make the login page work. However, it wasn't connected to anything since creating an account doesn't do anything and even trying to login with the admin doesn't even show sign of wrking (even when entering random number, it doesn't even say the name is wrong)


The Compose.yml (in Portainer using a stack)
````
services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-6044}:3000"
    depends_on:
      - server

  db:
    image: tobi312/rpi-postgresql-postgis:15-3.3-alpine-arm
    container_name: adventurelog-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-7044}:80"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/

volumes:
  postgres_data:
  adventurelog_media:
````

The environment variables:

<img width="748" alt="Image" src="https://github.com/user-attachments/assets/4f55a050-70d9-46ea-a24a-0263603ba9e6" />

**Comment by seanmorley15** [comment]
Hi @ChristopheRoyer21, looking at your config, I would make sure that you are accessing the app in your browser with `http://localhost:8044` exactly because what you access from needs to be the exact values of the `ORIGIN`. Also, make sure the port numbers are correct in `CSRF_TRUSTED_ORIGINS` I think you may have done `7055` instead of `7044` for the first one. After checking these, double check that the backend container was able to boot properly by checking the logs, a successful boot should mean a large ADVENTURELOG text prints. There is also an admin panel at `http://localhost:7044` you can see if that's accessible too. Let me know if these tips help!

**Comment by ChristopheRoyer21** [comment]
I'm currently accessing the application with `http://localhost:6044` I didn't mention `8044` anywhere in the config so maybe you did a typo? In any cases, I tried it, but no changes.
You were right for the `7055` in the `CSRF_TRUSTED_ORIGINS` totally a typo on my end.

As for the admin panel, I never manage to get it to work:

![Image](https://github.com/user-attachments/assets/1a475599-4996-4974-aba8-2621443c2d05)

The backend is clearly the issue here.

**Comment by seanmorley15** [comment]
Sorry yeah I meant `6044` 😂. So it does seem like the backend is not starting, are you able to get the logs for that container because that would be super helpful for finding the issue here. If you can provide a message in the backend logs or just a copy of them I would be able to determine the cause pretty quickly :)

**Comment by ChristopheRoyer21** [comment]
Aahhhh lol, the problem is really clear with these logs! I should have look at this sooner
I probably didn't setup postgresql correctly
![Image](https://github.com/user-attachments/assets/6f04a3c9-199b-40ff-b041-cc0a86f251e1)

**Comment by seanmorley15** [comment]
Ok so this might be something with DB auth or similar, check the DB logs too and see what that says! If needed you can delete the DB volume and restart everything and that *might* clear certain issues with initialization. If not the logs there are usually pretty clear!

**Comment by ChristopheRoyer21** [comment]
![Image](https://github.com/user-attachments/assets/832048af-d42d-4e97-b709-73fdfc5a6b44)

Here as well the log is pretty clear. But in the environment variable, I set up the password and username, so I'm not sure what's the problem. I'm new to portainer so maybe I had to configure the variable somewhere else as well

**Comment by seanmorley15** [comment]
Hmm... that's weird, you can try possibly passing the values in more explicitly
```
  db:
    image: tobi312/rpi-postgresql-postgis:15-3.3-alpine-arm
    container_name: adventurelog-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER} # or just set value's directly here 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
```
It's likely a portainer thing because in normal docker setups this would work just find with the `.env` link. Not sure if this same kind of explicit variavble setup is needed for the other containers or not.
