### ISSUE TITLE
[BUG] Google API not working?

### ISSUE THREAD

**Issue by ChristopheRoyer21** [seanmorley15/AdventureLog#684]
**Describe the bug**
I setted up the Google API and in the app, it still uses the Open Maps embbed maps

**To Reproduce**
1.  Setup the Server with the Google API key
2. Look at the maps in the app

**Expected behavior**
We should see the maps from Google, right?

**Screenshots**

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/80b83b67-2934-4894-992a-044c6d39a756" />

**Docker Compose**
 ````
services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-6044}:3000"
    depends_on:
      - server
    environment:
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - ORIGIN=${ORIGIN}
      - BODY_SIZE_LIMIT=${BODY_SIZE_LIMIT}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

  db:
    image: tobi312/rpi-postgresql-postgis:15-3.3-alpine-arm
    container_name: adventurelog-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-7044}:80"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ADMIN_USERNAME=${DJANGO_ADMIN_USERNAME}
      - DJANGO_ADMIN_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - DJANGO_ADMIN_EMAIL=${DJANGO_ADMIN_EMAIL}@email
      - DISABLE_REGISTRATION=${DISABLE_REGISTRATION}
      - PUBLIC_URL=${PUBLIC_URL}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - FRONTEND_URL=${FRONTEND_URL}
      
volumes:
  postgres_data:
  adventurelog_media:
```` 

And of course the ${name} are determined by the environment variables
